apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/farciniegas52/plataforma-transversal-kubernetes.git' # Ejemplo: https://github.com/usuario/repo.git
    targetRevision: HEAD
    path: infraestructura/namespaces # La ruta a la carpeta
  destination:
    server: 'https://kubernetes.default.svc' # Se instala en el mismo cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Crea el namespace si no existe