apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-balancers
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/farciniegas52/plataforma-transversal-kubernetes.git
    targetRevision: main
    path: componentes/application-load-balancers
    helm:
      releaseName: load-balancers
      valueFiles:
        - values.yaml
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
