apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.6.2
    
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: pragma-eks-platform-dev-eks-main
        vpcId: vpc-0d883b03c11d85fb4
        
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::034034141479:role/pragma-eks-platform-dev-role-eks-aws-lb-controller
        
        replicaCount: 2
        
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        
        region: us-east-1
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
