apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  
  sources:
    # Source 1: Helm chart oficial de AWS
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.6.2
      helm:
        releaseName: aws-load-balancer-controller
        valueFiles:
          - $values/componentes/aws-load-balancer-controller/values.yaml
    
    # Source 2: Repositorio Git con los values
    - repoURL: https://github.com/farciniegas52/plataforma-transversal-kubernetes.git
      targetRevision: main
      ref: values
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
