apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/farciniegas52/plataforma-transversal-kubernetes.git'
    targetRevision: HEAD
    path: componentes/namespaces # <--- Apunta a la receta que creamos arriba
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true